### ISSUE TITLE
Jukonun reposu ile birlikte sonuç vermiyor.

### ISSUE THREAD

**Issue by cartals** [altanozlu/TurkAnime-Downloader#2]
Yazın ilk zamanlarındaki gibi kullanayım dedim, sonuç vermiyor.

**Comment by altanozlu** [comment]
Cloudflare ddos koruması etkinleştirildiği için bozuldu sanırım.

**Comment by cartals** [comment]
Sorunu çözme şansın var mı ?

**Comment by altanozlu** [comment]
kodu tamamen değiştirmek gerek :/

**Comment by cartals** [comment]
Hiç değmez o zaman hocam, teşekkürler :)

**Comment by gokaybiz** [comment]
cloudflare + recaptcha + obfuscated js ile koruyorlar su anda :)

**Comment by cartals** [comment]
Öh, arkadaş jdownloadera kaldık :/

**Comment by KebabLord** [comment]
şu [zımbırıtı](https://github.com/Kebablord/turkanime-indirici) zaten selenium tabanlıydı ama altanınki gibi bi arama sistemini seleniumda yapmak kulağa yorucu geliyor. Farewell friends ;-;
